# Generated by Django 5.2.2 on 2025-06-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_items_alter_order_email_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
