# Generated by Django 5.2.2 on 2025-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_order_items_orderitem'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='products_or_created_4e5fd7_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
    ]
