services:
  web-app:
    build: .
    container_name: "web_app"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./user_services:/application"
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:16.9-alpine3.22
    container_name: "database_container"
    hostname: "database"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"      
    env_file:
      - .env

volumes:
  postgres_data:
