# Generated by Django 5.2.2 on 2025-06-11 10:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='price',
        ),
        migrations.AddField(
            model_name='tariff',
            name='longevity_in_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 12, 10, 48, 14, 322709)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 11, 10, 48, 42, 955957)),
            preserve_default=False,
        ),
    ]
