# Generated by Django 5.2.3 on 2025-06-11 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='duration_in_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 16, 52, 14, 369304, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
