# Generated by Django 5.2.2 on 2025-06-11 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_tariff_price_tariff_longevity_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 11, 11, 44, 235355)),
        ),
    ]
