# Generated by Django 5.2.2 on 2025-06-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='longevity_in_days',
            new_name='duration_in_days',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
