# Generated by Django 5.2.2 on 2025-06-11 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_longevity_in_days_tariff_duration_in_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='price',
        ),
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
