# Generated by Django 5.2.2 on 2025-06-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='telegram_id',
            new_name='telegram_chat_id',
        ),
    ]
